var show;
jQ(document).ready(function(){	
	/// switch pages/templates view ///
	jQ("#show_pagetree").click(function(){		
		jQ("#page_tree").show();
		jQ("#template_tree").hide();		
		jQ("#show_temptree").removeClass('active');
		jQ("#roles_tree").hide();		
		jQ("#show_roletree").removeClass('active');
		jQ("#capab_tree").hide();		
		jQ("#show_capatree").removeClass('active');
		jQ("#users_tree").hide();		
		jQ("#show_usertree").removeClass('active');
		jQ(this).addClass('active');
	});
	jQ("#show_temptree").click(function(){		
		jQ("#template_tree").show();
		jQ("#page_tree").hide();
		jQ("#show_pagetree").removeClass('active');
		jQ("#roles_tree").hide();		
		jQ("#show_roletree").removeClass('active');
		jQ("#capab_tree").hide();		
		jQ("#show_capatree").removeClass('active');
		jQ("#users_tree").hide();		
		jQ("#show_usertree").removeClass('active');
		jQ(this).addClass('active');
	});
	jQ("#show_roletree").click(function(){		
		jQ("#roles_tree").show();
		jQ("#page_tree").hide();
		jQ("#show_pagetree").removeClass('active');
		jQ("#template_tree").hide();		
		jQ("#show_temptree").removeClass('active');
		jQ("#capab_tree").hide();		
		jQ("#show_capatree").removeClass('active');
		jQ("#users_tree").hide();		
		jQ("#show_usertree").removeClass('active');
		jQ(this).addClass('active');
	});
	jQ("#show_usertree").click(function(){		
		jQ("#users_tree").show();
		jQ("#page_tree").hide();
		jQ("#show_pagetree").removeClass('active');
		jQ("#template_tree").hide();		
		jQ("#show_temptree").removeClass('active');
		jQ("#roles_tree").hide();		
		jQ("#show_roletree").removeClass('active');
		jQ("#capab_tree").hide();		
		jQ("#show_capatree").removeClass('active');
		jQ(this).addClass('active');
	});
	jQ("#show_capatree").click(function(){		
		jQ("#capab_tree").show();
		jQ("#page_tree").hide();
		jQ("#show_pagetree").removeClass('active');
		jQ("#template_tree").hide();		
		jQ("#show_temptree").removeClass('active');
		jQ("#roles_tree").hide();		
		jQ("#show_roletree").removeClass('active');
		jQ("#users_tree").hide();		
		jQ("#show_usertree").removeClass('active');
		jQ(this).addClass('active');
	});
	if(show != undefined){
		jQ("#show_"+show+"tree").click();
	}else{
		jQ("#show_pagetree").click();
	}
})